# Generated by Django 3.1.1 on 2020-10-19 21:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(default=None, max_length=25)),
                ('event_datetime', models.DateTimeField(default=datetime.datetime(2020, 10, 19, 17, 59, 16, 424892))),
                ('event_description', models.CharField(default=None, max_length=250)),
                ('event_author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
