# Generated by Django 3.1.1 on 2020-10-19 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerevent',
            name='event_tags',
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 18, 33, 58, 375974)),
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='event_description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='event_title',
            field=models.CharField(max_length=25),
        ),
    ]
