# Generated by Django 3.1.1 on 2020-10-19 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_auto_20201019_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerevent',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 18, 43, 59, 808913)),
        ),
    ]
