# Generated by Django 3.1.1 on 2020-10-21 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0006_auto_20201020_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerevent',
            name='cover',
            field=models.ImageField(default='me_as_tank_engine.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 9, 11, 5, 271670)),
        ),
    ]
