# Generated by Django 3.1.1 on 2020-10-24 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0010_auto_20201021_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerevent',
            name='cover',
            field=models.ImageField(default='stock/thomas.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 24, 15, 49, 57, 914308)),
        ),
    ]
