# Generated by Django 3.1.1 on 2020-10-21 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_auto_20201021_1259'),
        ('volunteer', '0010_auto_20201021_1553'),
    ]

    operations = [
    ]
