# Generated by Django 3.1.1 on 2020-10-25 18:01

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteer', '0011_merge_20201021_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerevent',
            name='cover',
            field=models.ImageField(default='stock/thomas.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 14, 1, 40, 422431)),
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventlist', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
