# Generated by Django 3.1.1 on 2020-10-25 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0012_auto_20201025_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerevent',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 14, 32, 9, 580507)),
        ),
    ]
