# Generated by Django 3.1.1 on 2020-10-27 03:45

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0014_auto_20201025_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerevent',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 26, 23, 45, 11, 392224)),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='eventlist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None),
        ),
    ]
