# Generated by Django 3.1.1 on 2020-10-27 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0015_auto_20201026_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='numofevents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 11, 39, 43, 665138)),
        ),
    ]
