# Generated by Django 3.1.1 on 2020-10-27 19:50

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0016_auto_20201027_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerevent',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 15, 50, 41, 608900)),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='eventlist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None),
        ),
    ]
