# Generated by Django 3.1.1 on 2020-10-27 20:30

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteer', '0020_auto_20201027_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerevent',
            name='attending',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 16, 30, 50, 721978)),
        ),
    ]
