# Generated by Django 3.1.1 on 2020-10-27 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0021_auto_20201027_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerevent',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 16, 38, 52, 206732)),
        ),
        migrations.DeleteModel(
            name='VolunteerProfile',
        ),
    ]
