# Generated by Django 3.1.1 on 2020-10-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0022_auto_20201027_1638'),
        ('volunteer', '0011_auto_20201024_1549'),
    ]

    operations = [
    ]
