# Generated by Django 3.1.1 on 2020-10-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0012_auto_20201028_1239'),
        ('volunteer', '0022_auto_20201027_1638'),
    ]

    operations = [
    ]
