# Generated by Django 3.1.1 on 2020-10-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0023_merge_20201028_1244'),
        ('volunteer', '0024_auto_20201028_1325'),
    ]

    operations = [
    ]
