# Generated by Django 3.1.1 on 2020-11-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0026_auto_20201108_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerevent',
            name='event_location',
            field=models.CharField(default='Rotunda Steps', max_length=100),
        ),
    ]
