# Generated by Django 3.1.1 on 2020-11-10 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteer', '0027_volunteerevent_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerevent',
            name='event_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
