# Generated by Django 3.1.1 on 2020-11-11 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteer', '0028_auto_20201109_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerevent',
            name='event_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events_written', to=settings.AUTH_USER_MODEL),
        ),
    ]
